import type { GmlFunction } from './gmlBuiltins'

type GmlEntry = [name: string, signature: string, description: string, category: string]

// Core GMS 1.4 functions documented on legacy manual pages that are absent from the generated list.
const entries: GmlEntry[] = [
  ["abs", "abs(val)", "Returns the absolute value of a value.", "Maths"],
  ["arccos", "arccos(x)", "Returns the inverse cosine of x.", "Maths"],
  ["arcsin", "arcsin(x)", "Returns the inverse sine of x.", "Maths"],
  ["arctan", "arctan(x)", "Returns the inverse tangent of x.", "Maths"],
  ["arctan2", "arctan2(y, x)", "Calculates arctan(y/x) and returns an angle in the correct quadrant.", "Maths"],
  ["ceil", "ceil(val)", "Returns the given number rounded up to the nearest integer.", "Maths"],
  ["choose", "choose(value1, value2, ...)", "Randomly chooses one of of a set of arguments.", "Maths"],
  ["cos", "cos(val)", "Returns the cosine of val.", "Maths"],
  ["darccos", "darccos(val)", "Returns the inverse cosine of val, where val is in degrees.", "Maths"],
  ["darcsin", "darcsin(x)", "Returns the inverse sine of val, where val is in degrees.", "Maths"],
  ["darctan", "darctan(x)", "Returns the inverse tangent of val, where val is in degrees.", "Maths"],
  ["darctan2", "darctan2(y, x)", "Calculates arctan(y/x) and returns an angle in the correct quadrant.", "Maths"],
  ["dcos", "dcos(val)", "Returns the cosine of val, where val is in degrees.", "Maths"],
  ["degtorad", "degtorad(deg)", "Converts the given degrees to radians.", "Maths"],
  ["device_mouse_check_button", "device_mouse_check_button(device, button)", "Returns whether a given device button is currently down.", "Mouse, Keyboard and Other Controls"],
  ["device_mouse_check_button_pressed", "device_mouse_check_button_pressed(device, button)", "Returns whether a given device button has been pressed.", "Mouse, Keyboard and Other Controls"],
  ["device_mouse_check_button_released", "device_mouse_check_button_released(device, button)", "Returns whether a given device button has been released.", "Mouse, Keyboard and Other Controls"],
  ["device_mouse_dbclick_enable", "device_mouse_dbclick_enable(bool)", "Sets whether a double left-click should be detected as mb_right or not.", "Mouse, Keyboard and Other Controls"],
  ["device_mouse_raw_x", "device_mouse_raw_x(device)", "Returns the x position of the device when pressed.", "Mouse, Keyboard and Other Controls"],
  ["device_mouse_raw_y", "device_mouse_raw_y(device)", "Returns the y position of the device when pressed.", "Mouse, Keyboard and Other Controls"],
  ["device_mouse_x", "device_mouse_x(device)", "Returns the x position of the device when pressed.", "Mouse, Keyboard and Other Controls"],
  ["device_mouse_x_to_gui", "device_mouse_x_to_gui(device)", "Returns the x position of the mouse relative to the GUI layer when pressed.", "Mouse, Keyboard and Other Controls"],
  ["device_mouse_y", "device_mouse_y(device)", "Returns the y position of the device when pressed.", "Mouse, Keyboard and Other Controls"],
  ["device_mouse_y_to_gui", "device_mouse_y_to_gui(device)", "Returns the x position of the mouse relative to the GUI layer when pressed.", "Mouse, Keyboard and Other Controls"],
  ["display_get_dpi_x", "display_get_dpi_x()", "Returns the dpi value of the x axis of the display.", "Windows And Views"],
  ["display_get_dpi_y", "display_get_dpi_y()", "Returns the dpi value of the y axis of the display.", "Windows And Views"],
  ["display_get_gui_height", "display_get_gui_height()", "Returns the height of the GUI.", "Windows And Views"],
  ["display_get_gui_width", "display_get_gui_width()", "Returns the width of the GUI.", "Windows And Views"],
  ["display_get_height", "display_get_height()", "Returns the height of the display.", "Windows And Views"],
  ["display_get_width", "display_get_width()", "Returns the width of the display.", "Windows And Views"],
  ["display_get_windows_alternate_sync", "display_get_windows_alternate_sync()", "Get the current vertical synchronisation method (Windows Only).", "Windows And Views"],
  ["display_get_windows_vertex_buffer_method", "display_get_windows_vertex_buffer_method()", "Gets the buffer method used on the Windows target platform.", "Windows And Views"],
  ["display_mouse_get_x", "display_mouse_get_x()", "Returns the x coordinate of the mouse relative to the display.", "Windows And Views"],
  ["display_mouse_get_y", "display_mouse_get_y()", "Returns the y coordinate of the mouse relative to the display.", "Windows And Views"],
  ["display_mouse_set", "display_mouse_set(x, y)", "Sets the position of the mouse on the display to the indicated values.", "Windows And Views"],
  ["display_reset", "display_reset(aa, vsync)", "Resets the display and changes the anti-aliasing filtering and vsync.", "Windows And Views"],
  ["display_set_gui_maximise", "display_set_gui_maximise(xscale, yscale, xoffset, yoffset)", "Scales the GUI to the given width or height.", "Windows And Views"],
  ["display_set_gui_size", "display_set_gui_size(width, height)", "Scales the GUI to the given width or height.", "Windows And Views"],
  ["display_set_ui_visibility", "display_set_ui_visibility(flags)", "Scales the GUI to the given width or height.", "Windows And Views"],
  ["display_set_windows_alternate_sync", "display_set_windows_alternate_sync(flag)", "Set the vertical synchronisation method (Windows Only).", "Windows And Views"],
  ["display_set_windows_vertex_buffer_method", "display_set_windows_vertex_buffer_method(method)", "Sets the buffer method used on the Windows target platform.", "Windows And Views"],
  ["ds_map_add_list", "ds_map_add_list(id, key, value)", "Adds a previously created ds_list to a given ds_map.", "Data Structures"],
  ["ds_map_add_map", "ds_map_add_map(id, key, value)", "Adds a previously created ds_map to a given ds_map.", "Data Structures"],
  ["ds_map_clear", "ds_map_clear(id)", "Clears all of the data from a given map.", "Data Structures"],
  ["ds_map_destroy", "ds_map_destroy(id)", "Destroys a given map permanently, removing it from memory.", "Data Structures"],
  ["ds_map_exists", "ds_map_exists(id, key)", "Returns if the given key exists or not in the ds_map specified.", "Data Structures"],
  ["ds_map_find_first", "ds_map_find_first(id)", "Finds and returns the first key, as stored by the computer, in the ds_map.", "Data Structures"],
  ["ds_map_find_next", "ds_map_find_next(id, key)", "Finds and returns the next key in the ds_map after the one specified in the function.", "Data Structures"],
  ["ds_map_find_previous", "ds_map_find_previous(id, key)", "Finds and returns the previous key in the ds_map above the one specified in the function.", "Data Structures"],
  ["ds_map_find_value", "ds_map_find_value(id, key)", "Finds the key specified and returns the paired value from the ds_map.", "Data Structures"],
  ["ds_map_read", "ds_map_read(id, str [, legacy])", "Reads the map data structure from a string.", "Data Structures"],
  ["ds_map_replace", "ds_map_replace(id, key, val)", "Replaces the value of a given key in the map with a new value.", "Data Structures"],
  ["ds_map_replace_list", "ds_map_replace_list(id, key, value)", "Replace a list with another list after it has been added to a ds_map.", "Data Structures"],
  ["ds_map_replace_map", "ds_map_replace_map(id, key, value)", "Replace a ds_map that has been previously added into a distinct ds_map, with another ds_map.", "Data Structures"],
  ["ds_map_secure_load", "ds_map_secure_load(filename)", "This function will create a ds_map containing the key/value data from a secure file.", "Data Structures"],
  ["ds_map_secure_load_buffer", "ds_map_secure_load_buffer(buffer)", "This function will load a secure saved DS map from a buffer. You must previously have loaded the buffer into memory (using buffer_load) and then passing that into this function will return a DS map populated with the contents of the buffer. Note that the buffer must have been created using the function ds_map_secure_save_buffer for this to work correctly.", "Data Structures"],
  ["ds_map_secure_save", "ds_map_secure_save(map, filename)", "This function will save the given ds_map to a secure location on the target platform.", "Data Structures"],
  ["ds_map_secure_save_buffer", "ds_map_secure_save_buffer(id, buffer)", "This function will save a previously created DS map to a buffer. You supply the DS map ID value (as returned by the function ds_map_create) and the ID of the buffer to write to (as returned by the function buffer_create).", "Data Structures"],
  ["ds_map_size", "ds_map_size(id)", "Returns the size of given ds_map.", "Data Structures"],
  ["ds_map_write", "ds_map_write(id)", "This function writes the data from a ds_map as a string.", "Data Structures"],
  ["dsin", "dsin(val)", "Returns the sine of val, where val is in degrees.", "Maths"],
  ["dtan", "dtan(val)", "Returns the tangent of val, where val is in degrees.", "Maths"],
  ["event_perform", "event_perform(type, numb)", "Performs a given event of the calling instance.", "Objects and Instances"],
  ["event_perform_object", "event_perform_object(obj, type, numb)", "Performs a given event of the specified object.", "Objects and Instances"],
  ["exp", "exp(n)", "The exponential function.", "Maths"],
  ["floor", "floor(n)", "Returns the given number rounded down to the nearest integer.", "Maths"],
  ["frac", "frac(n)", "Returns the decimal part of the given number.", "Maths"],
  ["immersion_play_effect", "immersion_play_effect(effect)", "Play a haptic effect.", "Mouse, Keyboard and Other Controls"],
  ["immersion_stop", "immersion_stop()", "Stop a haptic effect.", "Mouse, Keyboard and Other Controls"],
  ["ini_write_real", "ini_write_real(section, key, value)", "Writes a real value (number) to an.ini file.", "File Handling"],
  ["instance_activate_all", "instance_activate_all()", "Activates all instances in the room.", "Objects and Instances"],
  ["instance_activate_object", "instance_activate_object(obj)", "Activates all instances of a given object in the room, or a particular instance if you provide an id.", "Objects and Instances"],
  ["instance_activate_region", "instance_activate_region(left, top, width, height, inside)", "Activates all instances inside or outside the given region.", "Objects and Instances"],
  ["instance_deactivate_all", "instance_deactivate_all(notme)", "Deactivates all instances in the room.", "Objects and Instances"],
  ["instance_deactivate_object", "instance_deactivate_object(obj)", "Deactivates all instances of a given object in the room, or a particular instance if you provide an id.", "Objects and Instances"],
  ["instance_deactivate_region", "instance_deactivate_region(left, top, width, height, inside, notme)", "Deactivates all instances inside (or outside) the given region.", "Objects and Instances"],
  ["instance_find", "instance_find(obj, n)", "Returns the id of the (n)th instance of a given object.", "Objects and Instances"],
  ["int64", "int64(val)", "Attempts to convert a value into a 64bit integer.", "Maths"],
  ["irandom", "irandom(n)", "Returns a random integer between 0 and n. This includes n if n itself is an integer value.", "Maths"],
  ["irandom_range", "irandom_range(n1, n2)", "Returns a random integer between n1 and n2.", "Maths"],
  ["is_array", "is_array(variable)", "Checks a variable to see if it is an array or not.", "Miscellaneous"],
  ["is_bool", "is_bool(n)", "Returns whether the given argument is a boolean value.", "Miscellaneous"],
  ["is_int32", "is_int32(n)", "Returns whether the given argument is an int32.", "Miscellaneous"],
  ["is_int64", "is_int64(n)", "Returns whether the given argument is an int64.", "Miscellaneous"],
  ["is_matrix", "is_matrix(n)", "Returns whether the given argument is a matrix.", "Miscellaneous"],
  ["is_ptr", "is_ptr(n)", "Returns whether the given argument is a pointer.", "Miscellaneous"],
  ["is_real", "is_real(n)", "Returns whether the given argument is a real (as opposed to a string).", "Miscellaneous"],
  ["is_string", "is_string(n)", "Returns whether the given argument is a string (as opposed to a real).", "Miscellaneous"],
  ["is_undefined", "is_undefined(n)", "Returns whether the given argument is undefined or not.", "Miscellaneous"],
  ["is_vec3", "is_vec3(n)", "Returns whether the given argument is a vec3.", "Miscellaneous"],
  ["is_vec4", "is_vec4(n)", "Returns whether the given argument is a vec4.", "Miscellaneous"],
  ["lengthdir_x", "lengthdir_x(len, dir)", "Returns the horizontal x-component of the vector determined by the indicated length and direction.", "Maths"],
  ["lengthdir_y", "lengthdir_y(len, dir)", "Returns the horizontal y-component of the vector determined by the indicated length and direction.", "Maths"],
  ["ln", "ln(n)", "Returns the natural logarithm of the input value.", "Maths"],
  ["log10", "log10(n)", "Returns the log base 10 of n.", "Maths"],
  ["log2", "log2(n)", "Returns the log base 2 of n, the number 2 must be powered by to equal n.", "Maths"],
  ["logn", "logn(n, val)", "Returns the log base n of val.", "Maths"],
  ["make_colour_hsv", "make_colour_hsv(hue, sat, val)", "Returns a colour based on hue, saturation and value.", "Drawing"],
  ["make_colour_rgb", "make_colour_rgb(red, green, blue)", "Returns a colour based on the mix of red, green and blue component values.", "Drawing"],
  ["math_get_epsilon", "math_get_epsilon()", "Get the \"machine epsilon\" for floating point calculations.", "Maths"],
  ["math_set_epsilon", "math_set_epsilon(epsilon)", "Set the \"machine epsilon\" for floating point calculations.", "Maths"],
  ["max", "max(value1, value2, ...)", "Returns the largest of a set of real value arguments.", "Maths"],
  ["mean", "mean(value1, value2, ...)", "Returns the mean (average) of of a set of real value arguments.", "Maths"],
  ["median", "median(value1, value2, ...)", "Returns the median (middle number) of a set of real value arguments.", "Maths"],
  ["min", "min(value1, value2, ...)", "Returns the smallest of a set of real value arguments.", "Maths"],
  ["object_exists", "object_exists(obj)", "Returns whether an object with the given index exists or not.", "Objects and Instances"],
  ["object_get_depth", "object_get_depth(obj)", "Returns the depth of the specified object.", "Objects and Instances"],
  ["object_get_mask", "object_get_mask(obj)", "Returns the mask_index of the specified object.", "Objects and Instances"],
  ["object_get_name", "object_get_name(obj)", "Returns the name of the specified object as defined in the resource tree.", "Objects and Instances"],
  ["object_get_parent", "object_get_parent(obj)", "Returns the parent of the specified object.", "Objects and Instances"],
  ["object_get_persistent", "object_get_persistent(obj)", "Returns if the specified object is flagged as persistent or not.", "Objects and Instances"],
  ["object_get_physics", "object_get_physics(obj)", "Returns whether an object is flagged as physics enabled or not.", "Objects and Instances"],
  ["object_get_solid", "object_get_solid(obj)", "Returns whether an object has solid flagged as true or not.", "Objects and Instances"],
  ["object_get_sprite", "object_get_sprite(obj)", "Returns the sprite_index of the specified object.", "Objects and Instances"],
  ["object_get_visible", "object_get_visible(obj)", "Returns whether an object is flagged as visible or not.", "Objects and Instances"],
  ["object_is_ancestor", "object_is_ancestor(obj, par)", "Returns whether an object is the parent of another.", "Objects and Instances"],
  ["os_lock_orientation", "os_lock_orientation(flag)", "This function locks the game orientation to the device's current orientation.", "Operating System"],
  ["os_powersave_enable", "os_powersave_enable(flag)", "Set the powersave functions of the device.", "Operating System"],
  ["path_add", "path_add()", "Adds an empty path and returns its index.", "Paths"],
  ["path_add_point", "path_add_point(index, x, y, speed)", "Adds a point to the given path.", "Paths"],
  ["path_append", "path_append(index, path)", "Joins two paths together.", "Paths"],
  ["path_assign", "path_assign(index, path)", "Duplicates an existing path.", "Paths"],
  ["path_change_point", "path_change_point(index, n, x, y, speed)", "Changes an existing path points attributes.", "Paths"],
  ["path_clear_points", "path_clear_points(index)", "Deletes all the points in a given path.", "Paths"],
  ["path_delete", "path_delete(index)", "Deletes a given path.", "Paths"],
  ["path_delete_point", "path_delete_point(ind, n)", "Deletes a point from an existing path.", "Paths"],
  ["path_duplicate", "path_duplicate(index)", "Duplicates an existing path, returning its index.", "Paths"],
  ["path_end", "path_end()", "Ends the path the calling instance is currently following.", "Paths"],
  ["path_flip", "path_flip(index)", "Flips the given path along the horizontal axis with respect to its center.", "Paths"],
  ["path_insert_point", "path_insert_point(index, n, x, y, speed)", "Inserts a point into the given path at a set position.", "Paths"],
  ["path_mirror", "path_mirror(index)", "Flips the given path along the vertical axis with respect to its center.", "Paths"],
  ["path_rescale", "path_rescale(index, xscale, yscale)", "Scales the given path with respect to its center.", "Paths"],
  ["path_reverse", "path_reverse(index)", "Reverses the given path.", "Paths"],
  ["path_rotate", "path_rotate(index, angle)", "Rotates the given path with respect to its center.", "Paths"],
  ["path_set_closed", "path_set_closed(index, closed)", "Flags the given path as being closed or open.", "Paths"],
  ["path_set_kind", "path_set_kind(index, val)", "Sets the kind of connections of the path with the given index.", "Paths"],
  ["path_set_precision", "path_set_precision(index, prec)", "Sets the precision of the given path.", "Paths"],
  ["path_shift", "path_shift(index, xshift, yshift)", "Shifts the given path any number of pixels horizontally and vertically.", "Paths"],
  ["physics_fixture_set_kinematic", "physics_fixture_set_kinematic(fixture)", "This function indicates that the fixture is indicated to behave kinematically.", "Physics"],
  ["point_distance", "point_distance(x1, y1, x2, y2)", "Returns the length of a vector comprised of the specified components.", "Maths"],
  ["point_distance_3d", "point_distance_3d(x1, y1, z1, x2, y2, z2)", "Returns the length of a vector comprised of the specified components.", "Maths"],
  ["power", "power(x, n)", "Returns the given number to the given power; the number x multiplied by itself n number of times.", "Maths"],
  ["ptr", "ptr(n)", "Attempts to converts a given value into a pointer.", "Miscellaneous"],
  ["radtodeg", "radtodeg(rad)", "Converts radians to degrees.", "Maths"],
  ["random", "random(n)", "Returns a random real number between 0 and n.", "Maths"],
  ["random_get_seed", "random_get_seed()", "Returns the current random seed.", "Maths"],
  ["random_range", "random_range(n1, n2)", "Returns a random real number between n1 and n2.", "Maths"],
  ["random_set_seed", "random_set_seed(val)", "Sets the seed from which random numbers and outcomes are taken.", "Maths"],
  ["random_use_old_version", "random_use_old_version(flag)", "Use the deprecated random number generator or the regular one.", "Maths"],
  ["randomize", "randomize()", "Sets the seed to a random value.", "Maths"],
  ["round", "round(n)", "Returns the given number rounded to the nearest integer.", "Maths"],
  ["sign", "sign(n)", "Returns the sign of n.", "Maths"],
  ["sin", "sin(val)", "Returns the sine of val (val in radians).", "Maths"],
  ["sqr", "sqr(val)", "Returns val*val.", "Maths"],
  ["sqrt", "sqrt(val)", "Returns the square root of val. Val cannot be a negative value.", "Maths"],
  ["string_format", "string_format(val, tot, dec)", "Turns a real number into a string using your own formatting.", "Strings"],
  ["tan", "tan(val)", "Returns the tangent of val.", "Maths"],
  ["typeof", "typeof(variable)", "Returns the type of variable being checked as a string.", "Miscellaneous"],
  ["window_mouse_set", "window_mouse_set(x, y)", "Sets the position of the mouse in the window to the indicated values.", "Windows And Views"],
]

export const gmlCoreFunctions: GmlFunction[] = entries.map(
  ([name, signature, description, category]) => ({ name, signature, description, category })
)

