import { randomInt, randomUUID } from 'node:crypto'
import { mkdir, mkdtemp, rename, rm, stat, writeFile } from 'node:fs/promises'
import { basename, dirname, join, resolve } from 'node:path'

const comment = '<!--This Document is generated by GameMaker, if you edit it by hand then you do so at your own risk!-->'

function projectFilePath(path: string): string {
  if (/\.project\.gmx$/i.test(path)) return path
  if (/\.project$/i.test(path)) return `${path}.gmx`
  if (/\.gmx$/i.test(path)) return `${path.slice(0, -4)}.project.gmx`
  return `${path}.project.gmx`
}

function projectName(value: string): string {
  const name = basename(value).replace(/\.project\.gmx$/i, '').trim()
  if (
    !name ||
    name.length > 100 ||
    /[<>:"/\\|?*\u0000-\u001f]/.test(name) ||
    /[. ]$/.test(name) ||
    /^(con|prn|aux|nul|com[1-9]|lpt[1-9])(?:\.|$)/i.test(name)
  ) {
    throw new Error('Enter a valid project name')
  }
  return name
}

function xml(value: string): string {
  return value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
}

async function exists(path: string): Promise<boolean> {
  try {
    await stat(path)
    return true
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return false
    throw error
  }
}

function projectSource(): string {
  return [
    comment,
    '<assets>',
    '  <Configs name="configs">',
    '    <Config>Configs\\Default</Config>',
    '  </Configs>',
    '  <NewExtensions/>',
    '  <sounds name="sound"/>',
    '  <sprites name="sprites"/>',
    '  <backgrounds name="backgrounds"/>',
    '  <paths name="paths"/>',
    '  <scripts name="scripts"/>',
    '  <shaders name="shaders"/>',
    '  <fonts name="fonts"/>',
    '  <timelines name="timelines"/>',
    '  <objects name="objects"/>',
    '  <rooms name="rooms">',
    '    <room>rooms\\room0</room>',
    '  </rooms>',
    '  <datafiles number="0" name="datafiles"/>',
    '  <constants number="0"/>',
    '  <help>',
    '    <rtf>help.rtf</rtf>',
    '  </help>',
    '  <TutorialState>',
    '    <IsTutorial>0</IsTutorial>',
    '    <TutorialName></TutorialName>',
    '    <TutorialPage>0</TutorialPage>',
    '  </TutorialState>',
    '</assets>',
    ''
  ].join('\r\n')
}

function configSource(name: string): string {
  const guid = `{${randomUUID().toUpperCase()}}`
  const gameId = randomInt(100_000_000, 1_000_000_000)
  const displayName = xml(name)
  return [
    comment,
    '<Config>',
    '  <Options>',
    `    <option_display_name>${displayName}</option_display_name>`,
    `    <option_windows_display_name>${displayName}</option_windows_display_name>`,
    `    <option_gameguid>${guid}</option_gameguid>`,
    `    <option_gameid>${gameId}</option_gameid>`,
    '    <option_game_speed>30</option_game_speed>',
    '    <option_use_new_audio>True</option_use_new_audio>',
    '    <option_windows_start_fullscreen>0</option_windows_start_fullscreen>',
    '    <option_windows_borderless>0</option_windows_borderless>',
    '    <option_windows_interpolate_pixels>0</option_windows_interpolate_pixels>',
    '    <option_windows_display_cursor>-1</option_windows_display_cursor>',
    '    <option_windows_resize_window>-1</option_windows_resize_window>',
    '    <option_windows_allow_fullscreen_switching>-1</option_windows_allow_fullscreen_switching>',
    '    <option_windows_scale>0</option_windows_scale>',
    '    <option_windows_vsync>0</option_windows_vsync>',
    '    <option_windows_sleep_margin>1</option_windows_sleep_margin>',
    '    <option_windows_save_location>0</option_windows_save_location>',
    '    <option_windows_texture_page>2048</option_windows_texture_page>',
    '    <option_audioGroupCount>1</option_audioGroupCount>',
    '    <option_textureGroup_count>1</option_textureGroup_count>',
    '    <option_textureGroups0>Default</option_textureGroups0>',
    '    <option_textureGroup0_scaled>0</option_textureGroup0_scaled>',
    '    <option_textureGroup0_nocropping>0</option_textureGroup0_nocropping>',
    '    <option_textureGroup0_border>2</option_textureGroup0_border>',
    '    <option_textureGroup0_parent>&lt;none&gt;</option_textureGroup0_parent>',
    '    <option_textureGroup0_targets>9223372036854775807</option_textureGroup0_targets>',
    '  </Options>',
    '  <ConfigConstants/>',
    '</Config>',
    ''
  ].join('\r\n')
}

function roomSource(): string {
  return [
    comment,
    '<room>',
    '  <caption></caption>',
    '  <width>640</width>',
    '  <height>480</height>',
    '  <vsnap>32</vsnap>',
    '  <hsnap>32</hsnap>',
    '  <isometric>0</isometric>',
    '  <speed>30</speed>',
    '  <persistent>0</persistent>',
    '  <colour>12632256</colour>',
    '  <showcolour>-1</showcolour>',
    '  <code></code>',
    '  <enableViews>0</enableViews>',
    '  <clearViewBackground>-1</clearViewBackground>',
    '  <clearDisplayBuffer>-1</clearDisplayBuffer>',
    '  <makerSettings/>',
    '  <backgrounds/>',
    '  <views/>',
    '  <instances/>',
    '  <tiles/>',
    '  <PhysicsWorld>0</PhysicsWorld>',
    '  <PhysicsWorldTop>0</PhysicsWorldTop>',
    '  <PhysicsWorldLeft>0</PhysicsWorldLeft>',
    '  <PhysicsWorldRight>640</PhysicsWorldRight>',
    '  <PhysicsWorldBottom>480</PhysicsWorldBottom>',
    '  <PhysicsWorldGravityX>0</PhysicsWorldGravityX>',
    '  <PhysicsWorldGravityY>10</PhysicsWorldGravityY>',
    '  <PhysicsWorldPixToMeters>0.1</PhysicsWorldPixToMeters>',
    '</room>',
    ''
  ].join('\r\n')
}

export async function createProject(selectedPath: string): Promise<string> {
  const selectedFile = resolve(projectFilePath(selectedPath))
  const name = projectName(selectedFile)
  const folderName = `${name}.gmx`
  const selectedFolder = dirname(selectedFile)
  const targetFolder = basename(selectedFolder).toLowerCase() === folderName.toLowerCase()
    ? selectedFolder
    : resolve(selectedFolder, folderName)
  const targetProject = resolve(targetFolder, `${name}.project.gmx`)
  if (await exists(targetFolder)) throw new Error(`A project folder named ${folderName} already exists`)

  const tempFolder = await mkdtemp(join(dirname(targetFolder), '.opengms-new-'))
  const stagedFolder = join(tempFolder, folderName)
  try {
    await Promise.all([
      mkdir(join(stagedFolder, 'Configs'), { recursive: true }),
      mkdir(join(stagedFolder, 'rooms'), { recursive: true })
    ])
    await Promise.all([
      writeFile(join(stagedFolder, `${name}.project.gmx`), projectSource(), 'utf8'),
      writeFile(join(stagedFolder, 'Configs', 'Default.config.gmx'), configSource(name), 'utf8'),
      writeFile(join(stagedFolder, 'rooms', 'room0.room.gmx'), roomSource(), 'utf8')
    ])
    await rename(stagedFolder, targetFolder)
  } finally {
    await rm(tempFolder, { recursive: true, force: true }).catch(() => undefined)
  }
  return targetProject
}
